on:
  push:
    branches:
    - main

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
    - name: Production Code
      uses: actions/checkout@v2
    - name: Filter paths
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          backend:
            - 'discord/**'
          frontend:
            - 'frontend/**'

  # JOB to build and test backend code
  backend:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    defaults:
      run:
        working-directory: discord
    # For pull requests it's not necessary to checkout the code
    steps:
      - name: Production Code
        uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - run: npm ci
      - run: npm run build
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_BACKEND_APP }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "discord"

  # JOB to build and test frontend code
  frontend:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Production Code
        uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - run: npm ci
      - run: npm run build
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_FRONTEND_APP }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "frontend"